### ISSUE TITLE
GPU-friendly spike detection [6]

### ISSUE THREAD

**Issue by bcumming** [eth-cscs/nestmc-proto#105]
user points estimate: 6
feature: #67 (GPU Support)

This task will implement more efficient spike detection on the GPU. On completion
1. spikes will be efficiently detected and communicated on host and GPU back ends
2. MPI communication of spikes will have been tested and validated on all back ends

Implementation details
* the hardware-specific backend provides an interface that
    * front end (i.e. the `cell_group`) can describe which compartments/locations must be watched (with threshold)
    * front end can periodically request a list of recorded "threshold crossings"
* the front end is responsible for translating the threshold crossings into pre-synaptic spikes

**Comment by halfflat** [comment]
Closed by PR #167
