### ISSUE TITLE
ccmod: Segfault with 'fixed' mod files

### ISSUE THREAD

**Issue by w-klijn** [eth-cscs/nestmc-proto#13]
modcc segfaults on a roughly fixed mod file produces by the C.Elegans software. 
The mod files produce correct results when run in NEURON

The errors in the original file are fixed by rewriting or deleting lines. These issues will be reported in seperate issues.

./modcc -t cpu -o file.txt generic_neuron_iaf_cell_segfault.mod
Segmentation fault

[generic_neuron_iaf_cell.txt](https://github.com/eth-cscs/nestmc-proto/files/513978/generic_neuron_iaf_cell.txt)
[generic_neuron_iaf_cell_segfault.txt](https://github.com/eth-cscs/nestmc-proto/files/513977/generic_neuron_iaf_cell_segfault.txt)

**Comment by bcumming** [comment]
This contains some features like WATCH that we don't support.

**Comment by bcumming** [comment]
It also calls `net_send()`, which we don't support currently.

**Comment by bcumming** [comment]
Wouter, can you find out what these statements are designed to do? Once we understand the intent, we can find a solution.

**Comment by w-klijn** [comment]
Added new issue with detailed description. Closing this issue for now.
Will reopen a new one withy more details if problems persist
