### ISSUE TITLE
master branch does not build

### ISSUE THREAD

**Issue by biddisco** [eth-cscs/nestmc-proto#130]
OSX Xcode 8, clang llvm, default options in cmake

```
/Users/biddisco/src/nestmc/mechanisms/multicore/pas.hpp:115:17: error: no member named 'vec_area_' in
      'nest::mc::mechanisms::mechanism<nest::mc::multicore::backend>'
    using base::vec_area_;
          ~~~~~~^
In file included from /Users/biddisco/src/nestmc/src/backends/fvm_multicore.cpp:1:
In file included from /Users/biddisco/src/nestmc/src/backends/fvm_multicore.hpp:6:
/Users/biddisco/src/nestmc/src/mechanism.hpp:80:14: note: in instantiation of template class
      'nest::mc::mechanisms::pas::mechanism_pas<nest::mc::multicore::backend>' requested here
    typename M::view  vec_v,
             ^
In file included from /Users/biddisco/src/nestmc/src/backends/fvm_multicore.cpp:1:
/Users/biddisco/src/nestmc/src/backends/fvm_multicore.hpp:148:16: note: while substituting explicitly-specified template arguments into function template
      'make_mechanism'
        return mechanisms::make_mechanism<Mech<backend>>
               ^
/Users/biddisco/src/nestmc/src/backends/fvm_multicore.cpp:14:31: note: in instantiation of function template specialization
      'nest::mc::multicore::backend::maker<mechanisms::pas::mechanism_pas>' requested here
    { std::string("pas"),     maker<mechanisms::pas::mechanism_pas> },
                              ^
In file included from /Users/biddisco/src/nestmc/src/backends/fvm_multicore.cpp:1:
/Users/biddisco/src/nestmc/src/backends/fvm_multicore.hpp:148:16: error: no matching function for call to 'make_mechanism'
        return mechanisms::make_mechanism<Mech<backend>>
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/biddisco/src/nestmc/src/backends/fvm_multicore.cpp:14:31: note: in instantiation of function template specialization
      'nest::mc::multicore::backend::maker<mechanisms::pas::mechanism_pas>' requested here
    { std::string("pas"),     maker<mechanisms::pas::mechanism_pas> },
                              ^
In file included from /Users/biddisco/src/nestmc/src/backends/fvm_multicore.cpp:1:
In file included from /Users/biddisco/src/nestmc/src/backends/fvm_multicore.hpp:6:
/Users/biddisco/src/nestmc/src/mechanism.hpp:79:6: note: candidate template ignored: substitution failure [with M =
      nest::mc::mechanisms::pas::mechanism_pas<nest::mc::multicore::backend>]
auto make_mechanism(
     ^
```

**Comment by bcumming** [comment]
Can you try deleting the `hpp` files in `/mechanisms/multicore`?
These are generated from the DSL using the source to source compiler, and are not regenerated when the source to source compiler is modified. So if you modify the compiler, or if the compiler is modified by a merge, then the stale header files might not work anymore (which is the case here I beleive).

**Comment by biddisco** [comment]
For the less advanced user it is probably a good idea to ensure that when modcc or the *.mod files change, then the modcc compiler should rerun and regenerate the files. The expert user who wants to manually tweak the generated files should be able to disable auto-generation.

I propose that we add a cmake option "AUTO_RUN_MODCC_ON_CHANGES" (or something similar) which will be ON by default and you can disable it yourselves. Making it OFF by default would not impact your workflows, but would cause trouble for newbies, whereas the other way around will be safe for newbies, but you know what you're doing.

The new option would enable dependencies on the modcc compiler and *.mod files such that the generation step would be performed. 

I am happy to implement it.

**Comment by bcumming** [comment]
John, go for it!

Note that the CMake for building the mechanisms was simplified significantly by @halfflat and @vkarak just yesterday, so make sure you start hacking on the most recent version of master.

https://github.com/eth-cscs/nestmc-proto/blob/master/mechanisms/CMakeLists.txt

**Comment by biddisco** [comment]
It would appear that the changes on master branch for compiling the mod files now trigger a rebuild if the *.mod files or the modcc compiler are touched. The `build_all_mods` target does the right thing. I'll just add an option to isable it should you wish to not rebuild them due to hand crafted tweaks.
