### ISSUE TITLE
modcc: Scientific notation for small number leads to error

### ISSUE THREAD

**Issue by w-klijn** [eth-cscs/nestmc-proto#15]
When attempting to parse a line with a scientific notation for a small number an error is thrown:

 ./modcc -t cpu -o file.txt generic_neuron_iaf_cell.mod
error: generic_neuron_iaf_cell.mod:(line 43,col 34)
  PARAMETER block unexpected symbol '-'

line 42:     leakConductance = 1.00000005E-4 (uS)
[generic_neuron_iaf_cell.txt](https://github.com/eth-cscs/nestmc-proto/files/514034/generic_neuron_iaf_cell.txt)

**Comment by bcumming** [comment]
this should be a pretty straight-forward fix
