### ISSUE TITLE
Remove the OpenMP back end

### ISSUE THREAD

**Issue by bcumming** [eth-cscs/nestmc-proto#152]
The recently implemented `cthread` gives us a portable implementation threading implementation that supports task-based parallelism.

So the OpenMP back end, which doesn't support asynchronous tasks, isn't needed any more to provide portability to systems like BG/Q.

I am in favor of removing it, to reduce the overhead of maintaining it.

How do others feel about this proposal?

**Comment by halfflat** [comment]
I think the OpenMP back end is now redundant, and agree it should be deprecated given that `cthread` is portable and task-based.

**Comment by apeyser** [comment]
Agreed. OMP is inherently unscalable, adds maintenance cost twice, once by adding to cthread maintenance, second by being a mapping from two almost incommensurate models of multithreading.  Effort is better spent on expanding cthread along tbb lines where needed.

**Comment by bcumming** [comment]
I have turned this into a task, and assigned myself.
