### ISSUE TITLE
modcc: Declaring a state variable with (nA) unit leads to error

### ISSUE THREAD

**Issue by w-klijn** [eth-cscs/nestmc-proto#16]
When attempting to declare a state variable with (nA) as the unit an error occurs:

```
 ./modcc -t cpu -o file.txt generic_neuron_iaf_cell.txt
error: generic_neuron_iaf_cell.txt:(line 64,col 8)
  '(' is not a valid name for a state variable

63 STATE {
 64   vI (nA)   :
 65  }
```
Problem also occurs with (mA).
Removing the unit results 'fixes' the issue

[generic_neuron_iaf_cell.txt](https://github.com/eth-cscs/nestmc-proto/files/514079/generic_neuron_iaf_cell.txt)

**Comment by bcumming** [comment]
@vkarak, this should be cut and paste from other variable declaration blocks where units are assigned to variables.
