### ISSUE TITLE
Compilation error with nvcc and cthread back end

### ISSUE THREAD

**Issue by bcumming** [eth-cscs/nestmc-proto#168]
The GPU version of NestMC can't be compiled with the cthread back end because nvcc generates spurious errors when compiling the parallel sort implementation (the pss implementation from Intel).

The problem can be worked around by using `std::sort`, however this does increase initialization times. A better solution is to write our own, more robust sort.

**Comment by bcumming** [comment]
One way to fix this is to split target-specific code, like CUDA, for separate compilation. This would have the added benefit of letting us use C++14.

**Comment by apeyser** [comment]
Probably will be useful going forward with unknown issues on future architectures.

**Comment by bcumming** [comment]
We removed the parallel sort and just use `std::sort` for the cthread back end, which fixed the problem.
