### ISSUE TITLE
modcc: ? is not recognized as a comment

### ISSUE THREAD

**Issue by w-klijn** [eth-cscs/nestmc-proto#17]
end of line comment prepended with a ? leads to an error:

./modcc -t cpu -o file.txt generic_neuron_iaf_cell.txt
error: unexpected character '?' at (line 70,col 13)
generic_neuron_iaf_cell.txt:(line 70,col 13)
  expected a new line after call expression, found '?'

line 70:     rates() ? To ensure correct initialisation.

[generic_neuron_iaf_cell.txt](https://github.com/eth-cscs/nestmc-proto/files/514086/generic_neuron_iaf_cell.txt)

**Comment by vkarak** [comment]
Merged in #21.
