### ISSUE TITLE
make cthread the default threading model

### ISSUE THREAD

**Issue by bcumming** [eth-cscs/nestmc-proto#212]
Should we make cthread the default threading back end?

**Comment by halfflat** [comment]
Yes.

**Comment by apeyser** [comment]
Why?

**Comment by halfflat** [comment]
For me, because it is more portable than TBB, and by default exposes at least communication/compute overlap that the serial threading model does not.

**Comment by bcumming** [comment]
Because I would like to have threading support turned on by default, and cthread is available out of the box. TBB is the high-performance option, but it is not miles ahead.

**Comment by apeyser** [comment]
I'd agree that it's quite a bit preferable to the serial back-end as a default. In fact, the serial back-end really exists just as a developing/debugging tool and shouldn't ever be used in production runs.

**Comment by w-klijn** [comment]
Stuff working out of the box is always good.
