### ISSUE TITLE
Extend virtual cellgroup interface to expose cell type

### ISSUE THREAD

**Issue by w-klijn** [eth-cscs/nestmc-proto#238]
With the new virtual cell interface it is now possible to create different cell implementation with different capabilities. 
To position these cells correctly on the cluster 
and because we might need to treat them differently it should be possible to query the cell what type it is.

**Comment by w-klijn** [comment]
I think this should be as a name.
But also as capabilities. This would make it more general

Capabilities:
1. Can receive input
a. voltage
b. spikes
c. other
2. Sends spikes
3. Send voltages
4. detailed dendrite structure
5. Always on CPU

etc.
Should maybee have a small design session to make to as extendible as possible?

**Comment by w-klijn** [comment]
Optional Feature Pattern?
http://www.informit.com/articles/article.aspx?p=1252137&seqNum=2
Stream classes are examples of these: It would add a do function to each specific feature and throws not implemented when used incorrect. Although we might make the exception a little more informative like a special incorrect model specification exception

**Comment by bcumming** [comment]
addressed in PR #240
