### ISSUE TITLE
Model constructure should group cell of the same type together into cell groups.

### ISSUE THREAD

**Issue by w-klijn** [eth-cscs/nestmc-proto#239]
This appears to be a big change:
1. The type of the cell is only know at the moment we are already in the creation of the cell_group (with a range of gids to create)
  a. miniapp.cpp search for distribute_cells
 b. model.hpp see the constructor

2. I suggest adding a load balancer to our setup which would perform the current distribute cells but does more depending on the recipe.

Q. Would it be possible to have a indirect mapping between the gid as known in the recipe (user level)
and what we do internally? This would allow us to shuffle the neurons around with more ease.

Steps:
1. Refactor current functionality to add a tested loadbalancer
2. have the loadbalancer return cell_ranges with grouped neurons <- would need gid remapping

**Comment by w-klijn** [comment]
Depends on the cell_kind being available on the cell.

**Comment by bcumming** [comment]
I would break this task into some smaller tasks:
  1. implement a level of indirection between the recipe cell ordering and the ordering used by the NestMC library
  2. implement a load balancer, which would also require
  3. a method for assigning "weights" to cells that the load balancer would use to guide its decisions about where to place cells. This is non trivial, e.g. what if a cell has higher or lower overheads on CPU/GPU, or if a particular type of cell doesn't show any performance benefit until a minimum number are grouped together on the GPU.

**Comment by w-klijn** [comment]
sam [3:59 PM] 
Yep. Doing this properly needs the global permutation between public and internal gids, heuristics for load balancing, and all the associated communication and mapping. It's a lot of work.

[4:00] 
In the shorter term, I'm advocating that whatever recipe is generating these various cell types, groups them contiguously in ways that don't load balance too badly.

[4:00] 
Then the model would just group contiguous cells of the same type up to the group size (or per-cell type group size.)

[4:03] 
As a partial workaround, this simple but brittle procedure can be augmented with a recipe -> recipe translator that performs all the appropriate permutations given the number and types of nodes, and keeps the permutation for translation back again. This would be at the user (miniapp) level rather than nestmc library level.

[4:03] 
That would only be a stop-gap though before doing it properly in nestmc itself.

bcumming [4:07 PM] 
I am on this when I get back :wink:

[4:09] 
You are right that to do this right, we need some internal cell numbering that is different from the cell numbering that the user who supplies the model ueses.
As sam says, for now we just group cells of the same type together in the order they are supplied by the recipe.

**Comment by w-klijn** [comment]
I will break up the work: First with a simple version that groups cells at the recipe level.

**Comment by bcumming** [comment]
The cell-renumbering and load balancing work was finished in #326 and #334.
