### ISSUE TITLE
Add a neuron that spikes at set frequency

### ISSUE THREAD

**Issue by w-klijn** [eth-cscs/nestmc-proto#241]
As a in between step before adding the stochastic neuron add a neuron that replays spikes at regular intervals. 

Will exercise the same paths as the Stochastic neuron but is simpler in its implementation.

**Comment by bcumming** [comment]
I don't know if it is simpler, because you then have to deal with file IO. You have to settle on a file format, and implement robust parsing of the spike file input.

**Comment by bcumming** [comment]
An even simpler spike generating neuron would be one that generates spikes at a set frequency (i.e. with no stochasticity).

**Comment by w-klijn** [comment]
Implemented and merged
