### ISSUE TITLE
Should NestMC implement the parrot neuron?

### ISSUE THREAD

**Issue by w-klijn** [eth-cscs/nestmc-proto#243]
One common neuron type in NEST is the parrot neuron.

This neuron gets input from an other neuron (typically a Poisson neuron) and repeats the spikes.
This results in a with 'min delay' repeated spike.

https://github.com/nest/nest-simulator/blob/master/models/parrot_neuron.h

From Nest documentation:
Description:
The parrot neuron simply emits one spike for every incoming spike.
An important application is to provide identical poisson spike
trains to a group of neurons. The poisson_generator sends a different
spike train to each of its target neurons. By connecting one
poisson_generator to a parrot_neuron and then that parrot_neuron to
a group of neurons, all target neurons will receive the same poisson
spike train.
Remarks:
- Weights on connection to the parrot_neuron are ignored.
- Weights on connections from the parrot_neuron are handled as usual.
- Delays are honored on incoming and outgoing connections.
Only spikes arriving on connections to port 0 will be repeated.
Connections onto port 1 will be accepted, but spikes incoming
through port 1 will be ignored. This allows setting exact pre-
and post-synaptic spike times for STDP protocols by connecting
two parrot neurons spiking at desired times by, e.g., a
stdp_synapse onto port 1 on the post-synaptic parrot neuron.

**Comment by halfflat** [comment]
My first response is to say no, we shouldn't. This appears to have been created as a consequence of Nest's particular implementation of Poisson neurons.

In NestMC, this would simply be a matter of appropriate delays and weights in the connections to the one spike source. It doesn't even make sense in NestMC for the one spike source to generate independent spike streams — one could in theory have one 'cell' have multiple spike sources on it that were independent, but a) this wouldn't change the connection paradigm any, and b) it hardly seems like a win: they could just as easily, or even more easily, be implemented as single spike sources over multiple fake cells.

**Comment by bcumming** [comment]
Why not connect the source neuron (i.e. the Poisson generator in the example) to target cells directly?

The key question is what does it allow us to do that we can't do already?
