### ISSUE TITLE
Unit tests fail on KNL with AVX512 vector back-end.

### ISSUE THREAD

**Issue by halfflat** [eth-cscs/nestmc-proto#247]
Steps to repeat:
1. Build and compile for KNL:
```
% mkdir b; cd b
% CC=icc CXX=icpc cmake -DNMC_VECTORIZE_TARGET=KNL -DNMC_WITH_CUDA=OFF -DNMC_THREADING_MODEL=cthread -DNMC_WITH_ASSERTIONS=OFF -DCMAKE_BUILD_TYPE=debug ..
…
% make -j test.exe
…
```
2. Run unit tests `fvm_multi.init`, `probe.fvm_multicell`, or `mc_cell_group.test`.
```
% ./tests/test.exe --gtest_filter=fvm_multi.init
…
[ RUN      ] fvm_multi.init
…/tests/unit/test_fvm_multi.cpp:89: Failure
Value of: test_nan(mat.u(1, J.size()))
  Actual: false
Expected: true
…/tests/unit/test_fvm_multi.cpp:90: Failure
Value of: test_nan(mat.d)
  Actual: false
Expected: true
…/tests/unit/test_fvm_multi.cpp:91: Failure
Value of: test_nan(J.solution())
  Actual: false
Expected: true
[  FAILED  ] fvm_multi.init (1 ms)
…
```
```
% ./tests/test.exe --gtest_filter=probe.fvm_multicell
…
[ RUN      ] probe.fvm_multicell
…/tests/unit/test_probe.cpp:80: Failure
Value of: lcell.probe(probes[0])
  Actual: -nan
Expected: lcell.voltage()[probes[0].second]
Which is: -nan
…/tests/unit/test_probe.cpp:81: Failure
Value of: lcell.probe(probes[1])
  Actual: -nan
Expected: lcell.voltage()[probes[1].second]
Which is: -nan
[  FAILED  ] probe.fvm_multicell (1 ms)
…
```
```
% /tests/test.exe --gtest_filter=mc_cell_group.test
…
[ RUN      ] mc_cell_group.test
warning: solution out of bounds for cell 0 at (max) t 0.01 ms
warning: solution out of bounds for cell 0 at (max) t 0.02 ms
warning: solution out of bounds for cell 0 at (max) t 0.03 ms
…
warning: solution out of bounds for cell 0 at (max) t 50 ms
warning: solution out of bounds for cell 0 at (max) t 50 ms
…/tests/unit/test_mc_cell_group.cpp:39: Failure
Value of: group.spikes().size()
  Actual: 0
Expected: 4u
Which is: 4
[  FAILED  ] mc_cell_group.test (308 ms)
…
```

**Comment by halfflat** [comment]
Looks like a compiler bug.
```
$ icpc --version
icpc (ICC) 16.0.3 20160415
Copyright (C) 1985-2016 Intel Corporation.  All rights reserved.
```

Having trouble making a minimal test case, as it seems quite delicate. Something goes awry with the inlined version of `partition_range::bounds()`, where the second value in the pair is improperly computed (or whatever) as zero, in the middle of the `div_component_sampler` constructor.

This leads to it computing `scale_` as zero, so that all the returned divided compartments returned by the `div_component_integrator` (which derives from `div_component_sampler`) object are full of zero values, the lengths in particular. This in turn makes all the `face_conductance` values computed in the `fvm_multicell` initialization NaNs.

Trying to print the computed values within the `div_compartment_integrator` or base class constructor, or even print one of the constructor arguments, is sufficient to dodge the bad code generation. Similarly, building with `-inline-level=0` makes the problem go away.

**Comment by vkarak** [comment]
Let's try it also with Intel 17 on Tave.

**Comment by vkarak** [comment]
I could verify the bug with Intel 16 on Tave as well, but the code works fine with Intel 17.

```
module switch PrgEnv-cray PrgEnv-intel
module load gcc/6.3.0  # the trick to get a more recent libstdc++
cd build-knl/
CC=icc CXX=icpc cmake -DMODCC_BIN=../build-generic/modcc/modcc -DNMC_VECTORIZE_TARGET=KNL -DNMC_WITH_CUDA=OFF -DNMC_THREADING_MODEL=cthread -DNMC_WITH_ASSERTIONS=OFF -DCMAKE_BUILD_TYPE=debug ..
srun ./tests/test.exe
```
You need to compile separately `modcc`, since on Tave you're cross compiling for KNL.

```
icpc --version
```
```
icpc (ICC) 17.0.1 20161005
Copyright (C) 1985-2016 Intel Corporation.  All rights reserved.

```

**Comment by halfflat** [comment]
I have a patch which seems to force the appropriate evaluation. In `div_compartment_sampler` ctor, added the #if-guarded line below:
```
        segs_ = make_partition(offsets_, lengths);
#if defined(__INTEL_COMPILER_BUILD_DATE) && (__INTEL_COMPILER_BUILD_DATE<=20160415)
        compat::sink(segs_.bounds());
#endif
```

With `compat::sink` defined in `util/compat.hpp` by:
```
template <typename X>
inline void sink(const X& x) {
    char buf[sizeof x];
    volatile char* bufptr = buf;
    const char* xptr = reinterpret_cast<const char*>(&x);
    
    for (std::size_t i = 0; i<sizeof buf; ++i) {
        *bufptr++ = *xptr++;
    }
}       
```

The question is: do we actually incorporate this into the master branch? I guess it becomes a question of how reasonable it is to expect the systems in question to have the most recent icc version.

**Comment by w-klijn** [comment]
We could put it in a include with a clear name like: compiler issue bug fixes.
That makes clear the how and why, and keeps the code clean.

I'm always pro fixing stuff now, because of you get the question of the user in 2 years it might take you a day to remember that this was the problem. Put in clear source comments.

I know it is an issue outside of our control and external but a user does not see that, it just sees broken fragile code.

**Comment by halfflat** [comment]
Yeah, we're currently using `compat.hpp` to hold our various per-compiler work-around support code.

Rather than have the `#if`-guards in `compartment.hpp`, we could do something like the existing `compat::compiler_barrier_if_xlc_leq(unsigned version)` function, e.g. in `namespace compat`:
```
    template <typename X>
    void sink_if_icc_leq(unsigned version, const X& x) {
#if defined(__INTEL_COMPILER_BUILD_DATE)
        if (__INTEL_COMPILER_BUILD_DATE<=ver) {
            compat::sink(x);
        }
#endif
    }
```
and then use this function instead in the `div_compartment_sampler` constructor:
```
        segs_ = make_partition(offsets_, lengths);
        compat::sink_if_icc_leq(20160415u, segs_.bounds());
```
