### ISSUE TITLE
Investigate and address performance regression on async-integration branch.

### ISSUE THREAD

**Issue by halfflat** [eth-cscs/nestmc-proto#285]
Like-for-like comparisons of performance with the miniapp default networks between `devel/async-integration` and `master` indicate that the asynchronous integration code is barely affected by event delivery, but wears a significant overhead in time stepping.

Median time-stepping times over five runs on `greina7` (P100, 8 cores without hyperthreading):

| time (s) | branch | device | t | g | n |
|--:|--:|--:|--:|--:|--:|
|  9.62 | devel | cpu |  100 |    1 |  1000 |
| 95.67 | devel | cpu |  100 |    1 | 10000 |
|  9.30 | devel | cpu |  100 |    4 |  1000 |
|  0.69 | devel | gpu |  15 | 1000 |  1000 |
| 1.44 | devel | gpu |   30 | 1000 |  1000 |
|  6.22 | devel | gpu | 100 | 1000 |  1000 |
| 23.45 | devel | gpu |100 | 10000 | 10000 |
|  7.89 | master | cpu | 100 |    1 |  1000 |
| 78.32 | master | cpu |  100 |    1 | 10000 |
| 12.10 | master | cpu |  100 |    4 |  1000 |
|  0.56 | master | gpu |   15 | 1000 |  1000 |
| 26.75 | master | gpu |  30 | 1000 |  1000 |

Note that in these models, stopping at _t = 15_ avoids any event delivery. Times for the master branch gpu version with the default _t = 100_ took too long to be worth benchmarking.

Based on these figures, without event delivery, integration is taking approximately 22% longer on both CPU and GPU in the development branch:

| device | t | g | n | master (s) | devel (s) | overhead |
|--:|--:|--:|--:|--:|--:|--:|
| cpu | 100 | 1 | 1000 | 7.89 | 9.62 | 21.9% |
| gpu | 15 | 1000 | 1000 | 0.56 | 0.69 | 23.2% |

This overhead is likely larger than it need be: profile the code and reduce this overhead.

**Comment by halfflat** [comment]
The primary culprit is the added time in the `nrn_state()` function on simple exponential synapses: the indirect look-ups for `dt` calculation adds roughly 40% work to the function.

@bcumming proposes pre-computing cell `dt` values per compartment; this should remove at least two thirds of the added overhead in time-stepping.

**Comment by halfflat** [comment]
Update: implemented separate `dt` vector in (vide `devel/async-integration-dt-vec` branch at `halfflat/nestmc-proto`).

Performance appears to be 1-2% _slower_. Investigation continues.

**Comment by bcumming** [comment]
It is 1-2% on top of the 21-23% slowdown?

**Comment by halfflat** [comment]
Yup, it is moar slower.

**Comment by halfflat** [comment]
Updated comparison with the separate `dt` version:


| device | t | g | n | master (s) | devel (s) | devel-dt-vector (s) | old overhead | new overhead |
|--:|--:|--:|--:|--:|--:|--:|--:|--:|
| cpu | 100 | 1 | 1000 | 7.89 | 9.62 | **8.96** | 21.9% | **13.6%** |
| gpu | 15 | 1000 | 1000 | 0.56 | 0.69 | **0.72** | 23.2% | **28.6%** |

**Comment by bcumming** [comment]
The GPU is more sensitive to additional memory transactions because we operate in bandwidth limited mode on the GPU, whereas we optimize for cache on the CPU?

**Comment by halfflat** [comment]
I think that may have a lot to do with it. But it needs more of stick poked at it to be sure.

**Comment by halfflat** [comment]
If these different operation modes persist in having an optimization on one device penalize performance on another, we might need to consider splitting the device-specific implementations further, possibly to the point of having unicellular groups for 'multicore' with lower-overhead event handling.

**Comment by halfflat** [comment]
Despite the launch time of the first kernel in the integration step taking a surprisingly long time, the fundamental problem is that these kernels cannot be stacked up in advance owing to the explicit host-side loop termination check that happens each step.

Only doing the minimum time test when we have to, and only checking the times in the placeholder sampler code when there is a chance that a sampler could be triggered, reduces the overhead significantly.

| device | t | g | n | master (s) | devel (s) | devel-dt-vector-reduce-checks (s) | old overhead | new overhead |
|--:|--:|--:|--:|--:|--:|--:|--:|--:|
| cpu | 100 | 1 | 1000 | 7.89 | 9.62 | **8.85** | 21.9% | **12.2%** |
| gpu | 15 | 1000 | 1000 | 0.56 | 0.69 | **0.62** | 23.2% | **10.7%** |

**Comment by halfflat** [comment]
Addressed by #290 but we should consider specializations for synchronous (i.e. one cell or gap junction-connected cell group) and asynchronous (wide, GPU cell groups).
