### ISSUE TITLE
Write down formula and parameters for LIF cell [2]

### ISSUE THREAD

**Issue by bcumming** [eth-cscs/nestmc-proto#292]
Formulate the equations that describe the LIF cell and associated state/dynamics.
  * try to follow the interface/parameters used by NEST  http://www.nest-simulator.org/cc/iaf_neuron/
  * think about which parameters the user should be allowed to specify
  * specify the units of each variable

**Comment by kabicm** [comment]
The complete formulation of the LIF neuron model and its parameters is given at the following link:
https://www.overleaf.com/9974817gghfyqxqdytx#/36645046/
