### ISSUE TITLE
Warning: may be used uninitialized in this function

### ISSUE THREAD

**Issue by w-klijn** [eth-cscs/nestmc-proto#30]
When compiling on Julia (PCP machine) I get a warning with g++ 6.1.0
`Warning: '...' may be used uninitialized in this function`

It is in the file nestmc-proto/tests/validation/trace_analysis.hpp line 63
I had a look and cannot solve this easily.

```
In file included from /gpfs/homeb/pcp0/pcp0016/code/nestmc/trunk/nestmc-proto/tests/validation/validate_synapses.cpp:19:0:
/gpfs/homeb/pcp0/pcp0016/code/nestmc/trunk/nestmc-proto/tests/validation/trace_analysis.hpp: In function ‘void nest::mc::assert_convergence(nest::mc::conv_data<Param>&) [with Param = int]’:
/gpfs/homeb/pcp0/pcp0016/code/nestmc/trunk/nestmc-proto/tests/validation/trace_analysis.hpp:63:68: warning: ‘*((void*)& smallest_pd +24)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
     auto tbound = [](trace_peak p) { return std::abs(p.t)+p.t_err; };
```

**Comment by halfflat** [comment]
Yep, it's a curious one (for example, I don't see this locally with g++ 6.1, but Ben does with g++ 6.2).

I'm right now cleaning up this code to make it more comprehensible; with a bit of luck it will make g++ happy too.

**Comment by halfflat** [comment]
Could I ask if you still are getting the warning with the latest master? (It's not one that ever turned up in my development environment.(

**Comment by halfflat** [comment]
Going to close this one, as being fixed along the way. Re-open if it occurs for you!
