### ISSUE TITLE
Implement CPU backend for LIF neuron [4]

### ISSUE THREAD

**Issue by kabicm** [eth-cscs/nestmc-proto#303]
Implement CPU backend for LIF neuron (lif_cell_group.hpp).

Since this is the first version, we will make some simplifications:

1) ignore external current I_e and alpha-kernel, the input current is therefore just the sum of all the weights of incoming spikes.

2) integrate in jumps dt = min(t_final - t, t_event - t)

3) ignore binning policy and sampling

4) use general data types (use value_type instead of double)

5) make simple validation tests to check if the group is spiking properly

**Comment by bcumming** [comment]
Looks good to me. How much has already been implemented?

**Comment by kabicm** [comment]
The first three points + 2 very simple tests are already implemented. Now I need to refactor the code, use general data types and make more validation tests (with more than 1 neuron).

**Comment by bcumming** [comment]
By general data types, do you mean templates, e.g. allowing us of `float` or `double` for value types?

**Comment by kabicm** [comment]
Yes, exactly!
