### ISSUE TITLE
Spike input from file

### ISSUE THREAD

**Issue by w-klijn** [eth-cscs/nestmc-proto#306]
As a preparation to the first release it would be handy to have a method to input spikes without recompiling the whole project.
A straightforward way could be readout of spikes in a file.

In NEST this is solved outside of the simulator. There is a 'generic' spike generator neuron that emit spikes at times supplied as a array of spike times in Milliseconds.

To mirror this in XMC we would need:
1. A generator cell (and group) and description
2. A helper that parses the input from file and returns a vector of spike times
3. A unit test that validates the results
4. Documentation how it works.

Complications:
1. How fail save should the reading be? Python says fail early and hard
2. S separation between description and implementation: Parsed spike-times or path indescription?
To allows proper separation of concerns it should not be the path. This would delay the responsibility to the cell and complicate later stages when this input come from python
It does result in larger description.

Time estimation:
20Hrs

**Comment by halfflat** [comment]
I'd propose limiting file I/O within the core XMC library as much as possible — ideally, it would leave all that interaction to the calling code or support libraries. If we adopt this, then the description passed to the cell group would either be a concrete list of spike sources and times, or more generally a call-back function that can populate such a list for a given time interval.

In the interest of getting something useful working quickly, I'd go with the first one: the cell group would model a population of spiking sources with explicit spike times. These times and sources would then be provided by the description given by a recipe.

The actual file reading and error handling would then be provided by whatever the recipe uses to produce these descriptions when requested, or the reading could be performed first, outside the recipe implementation, and then those numbers given to the recipe explicitly. The former approach would be closer to the functional on-demand instantiation that we try to employ.

**Comment by w-klijn** [comment]
Ok, Ill perform the reading in the recipe with a helper function.

I will add the functionality at the same 'location' as the regular spiking neuron. 
Adding a simple switch would add the option to inject spikes from file instead of the single spike at the start. 
This minimal functionality is a clear green light for a complete function.

**Comment by bcumming** [comment]
Implementedin #314
