### ISSUE TITLE
Implement Poisson spiking neurons [2]

### ISSUE THREAD

**Issue by kabicm** [eth-cscs/nestmc-proto#317]
The goal is to implement a neuron model that produces spikes following the Poisson distribution. This neuron should only serve for producing spikes and should not be receiving any of the events.

**Comment by w-klijn** [comment]
You could have a look at:
https://github.com/eth-cscs/nestmc-proto/issues/75

It gives a complete overview of the needed functionality

Combined with the rss_cell it should be relative strait forward: It would mostly be the Poisson generation that needs to be implemented

https://github.com/eth-cscs/nestmc-proto/pull/314 is another example of a simple cell generating spikes
