### ISSUE TITLE
remove fancy fonts from LaTeX docs

### ISSUE THREAD

**Issue by bcumming** [eth-cscs/nestmc-proto#55]
Nonstandard LaTeX fonts should be avoided in the docs. Looking at you `passive_cable` docs...

https://github.com/eth-cscs/nestmc-proto/blob/master/docs/passive_cable/cable_computation.tex#L11

**Comment by halfflat** [comment]
TeX Gyre fonts 'should' be part of a full `texlive` install. They might be packaged differently under e.g. Arch Linux, or it could be a matter of them not being visible to `fontconfig`: see for example: (https://wiki.archlinux.org/index.php/TeX_Live#Fonts)

**Comment by bcumming** [comment]
They aren't in my TeXlive install, and I have the "full install".

**Comment by halfflat** [comment]
If it turns out this is a common TeX installation issue, I'll nuke the font. But: so pretty!

**Comment by bcumming** [comment]
I was able to install them separately. I am not so comfortable with making LaTeX any harder than it is to set up. If we get any more issues, the fonts get nuked.
