### ISSUE TITLE
Clean up GPU branch [10]

### ISSUE THREAD

**Issue by bcumming** [eth-cscs/nestmc-proto#61]
point estimate: 10 points
feature: #67

The GPU branch github.com/bcumming/nestmc-proto/tree/gpu needs to be merged with master. There are issues that make this difficult
  1. its "diff" is overwhelming relative to the master
  2. the quality of the code in this branch needs to be improved (types, comments, design, documentation)
  3. more work is required to get it ready for final merge: namely validation of the gpu results

This task aims to target steps 1 and 2 in a gpu branch of the main repository. Once the state of the branch is satisfactory, the validation in step 3 will be addressed in a separate project task.

Acceptance criteria
- all tests pass and validation pass for the CPU back end
- the CPU back end has unchanged performance relative to current master
- gpu version of tests and miniapp compiles and runs without crashing
- @halfflat approves the design and implementation of the cpu and gpu implementations

Steps
1. address @halfflat's comments in #45 [3]
2. add changes since #45 to the PR [4]
3. address @halfflat's comments on step (2) [3]

**Comment by halfflat** [comment]
Looks good to me!

**Comment by bcumming** [comment]
Finished the estimates. I went through your first code review and just made a quick tally of the small and large fixes, to come up with 6 points for me to make fixes, comment on the review, and then make further changes based on follow up review.

**Comment by bcumming** [comment]
Step 1 has been finished, and step 2 mostly finished. The backend implementation hasn't been fully polished, but I think that its structure is quite clear and fit for purpose.

**Comment by bcumming** [comment]
Step 2 has been finished, the PR #45 is ready for review.

**Comment by halfflat** [comment]
PR #45 merged!
