### ISSUE TITLE
Add KINETIC block parsing support to `modcc`

### ISSUE THREAD

**Issue by halfflat** [eth-cscs/nestmc-proto#62]
Point estimate: 6
Feature: #60 

* Extend lexer to support KINETIC-specific syntax: `KINETIC` keyword; `CONSERVE` keyword; `~` reaction introduction symbol; `<->` reaction arrows symbol; distinguish real and integral numbers.
* Extend parser to treat integral number expressions appropriately.
* Extend parser with an `Expression` sub-type for reactions and add any further sub-types for sub-components of a reaction.
* Add unit tests covering above.

Example kinetic block for validation:
```
PROCEDURE rates {
    : compute f1(v), r1(v) etc.
    ...
}

KINETIC kin {
    rates(v)
    ~ s1 <-> s2 (f1, r1)
    ~ s2 <-> s3 (f2, r2)
    ~ s2 <-> s4 (f3, r3)
    CONSERVE s1 + s3 + s4 - s2 = 1
}
```

**Comment by bcumming** [comment]
I think it is missing
- a brief description of what is being solved.
- breakdown of time to be spent on each of the steps.

**Comment by bcumming** [comment]
looks good.

**Comment by halfflat** [comment]
Will also support at the parsing phase multimolecular reaction forms, e.g.
```
~ 2c1 + c2 <-> c3
```

**Comment by halfflat** [comment]
PR #71 merged!
