### ISSUE TITLE
Analysis and implementation of Tridiagonal solvers on GPUs

### ISSUE THREAD

**Issue by pedrovalerolara** [eth-cscs/nestmc-proto#72]
NEST-MC implements currently a Thomas algorithm to solve tridiagonal systems.
Although this method is the optimal method in terms of number of operations, there are other methods which can solve the system in parallel, such as Parallel Cyclic Reduction (PCR), Cyclic Reduction, among others.
In particular, there is a subrutine called gtsvStridedBatch() in cuSPARSE (http://docs.nvidia.com/cuda/cusparse/#axzz4PL9ndAze) which can solve multiple tridiagonal systems in parallel using GPUs.

Moreover, we have the experience of implementing some of these methods in CUDA, see 
*Pedro Valero-Lara, Alfredo Pinelli, Julien Favier, Manuel Prieto-Matías:
Block Tridiagonal Solvers on Heterogeneous Architectures. ISPA 2012: 609-616
*Pedro Valero-Lara, Alfredo Pinelli, Manuel Prieto-Matías:
Fast finite difference Poisson solvers on heterogeneous architectures. Computer Physics Communications 185(4): 1265-1272 (2014) 

There is a problem regarding to the specific features of NEST-MC, as each of the tridiagonal systems can have different sizes, this makes difficult to use the cuSPARSE routine.
So, we are going to implement a cuda kernel which is able to deal with multiples systems with different sizes in parallel.

- Validate numerically the application by using a simple test case for systems with the same size and using cuSparse routine

- Implement new CUDA kernels for multiple tridiagonal systems with different sizes

-  Performance evaluation of the different approaches

**Comment by bcumming** [comment]
Sounds like an good plan. Note that the algorithm for solving Hines matrices have the same complexity as Thomas algorithm, but it isn't the same! The "branching" in the matrix structure complicates things a bit.
Each matrix in the set of matrices to solve has different
  * dimensions (as you have observed)
  * structure (i.e. the values in `p` are determined by the branching structure of each cell)
